### ISSUE TITLE
Detailed Installation Instructions

### ISSUE THREAD

**Issue by nk4456542** [Open-Book-Genome-Project/TheBestBookOn.com#23]
I know that there are installation instructions in the readme file of the project. As someone who is new to software development in general, I ran into some issues while setting up the project locally. As a small example, the port number of the Postgres in my computer is `5432` but the below line in the project specifies the port as `5433`
https://github.com/Open-Book-Genome-Project/TheBestBookOn.com/blob/ad899fbe483be5c082046e2f0b3f099f1490ca05/bestbook/configs/__init__.py#L48

So I will modify the instructions in the readme file to setup the project locally, which will hopefully help newcomers like me.

I had a question before progressing further to submit a PR:
Should I add a new file called `contributing.md` or modify the existing installation instructions in the readme file itself?

Thanks to @cclauss, for helping me setup it up locally.

## Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
I think the default port should **indeed** be `5432` -- if you'd like to open a PR, that would be great, thank you!
