### ISSUE TITLE
Unapproved recommendations are viewable in /browse

### ISSUE THREAD

**Issue by jamesachamp** [Open-Book-Genome-Project/TheBestBookOn.com#39]
`/browse` displays all recommendations regardless of whether or not they have been approved.  Is this desired?  My understanding is that only approved recommendations will be available for consumers of the site.

To correct, we'll have to check for `Recommendation.is_approved` to be `true` when fetching recommendations in `browse.html`.

**Comment by mekarpeles** [comment]
You're right -- yes, I think filtering recommendation on the /browse page to only those which have been approved is the right approach.

And should be relatively easy to do using the model in the template. There's a way to .query().filter (I believe) and there should also be an example on skillsera website. Or, we can just manually filter (list comprehension) to remove things which are not approved.
