### ISSUE TITLE
Submitting recommendation fails with a 500 error

### ISSUE THREAD

**Issue by jamesachamp** [Open-Book-Genome-Project/TheBestBookOn.com#46]
While testing recommendation submissions, a submission failed due to `lower()` being called on a null object in `Book.clean_olid()`.

`clean_olid` is called on each candidate book in a recommendation.

**Comment by cclauss** [comment]
Please provide the resulting Python stack trace.

**Comment by jamesachamp** [comment]
Here is the actual error:
`AttributeError: 'NoneType' object has no attribute 'lower' (ocaid.lower in File "/var/www/TheBestBookOn.com/bestbook/api/books.py", line 73, in clean_olid)`

@mekarpeles do you still have access to the stack trace?  I'm having trouble reproducing this error.

**Comment by jamesachamp** [comment]
I've discovered the root cause.  It is possible to submit the form without a winner or candidate by typing in the respective text input and not selecting a book from the autocomplete options.  Validating that the winner and all candidates have an OLID will solve this issue.

**Comment by cclauss** [comment]
Cool!  Now that we are Python 3-only, we can start to add type hints to document our type assumptions.
`def clean_olid(olid):` --> `def clean_olid(olid: str) -> str:`
* http://mypy-lang.org
* https://docs.python.org/3/library/typing.html
