### ISSUE TITLE
Create a new endpoint and view for viewing individual recommendations based on ID.

### ISSUE THREAD

**Issue by aasifkhan7** [Open-Book-Genome-Project/TheBestBookOn.com#50]
Because the Recommendation model has an `id` primary key

We can use a url scheme like:

`https://thebestbookon.com/recommendations/:id/:human-readable-slug` where the `human-readable-slug` is based on the subject of the recommendation (and is not required for the URL to work).

e.g. in both these urls the human readable portion is just for search engines and can be any value (the ID in the url makes sure the redirections occur correctly)
https://www.ebay.com/b/Lenovo-PC-Laptops-Netbooks-Lenovo-ThinkPad-T430/177/bn_99500305
https://www.amazon.com/-/us/aasif-is-great/dp/B002ND1UI8

i.e. Going to the `Recommendation.id` `:id` should work by itself, however for SEO purposes, we'd want it to redirect to
`https://thebestbookon.com/recommendations/:id`

**Comment by mekarpeles** [comment]
closed by #63
