### ISSUE TITLE
Expose endpoint to get a given user's observations

### ISSUE THREAD

**Issue by jamesachamp** [Open-Book-Genome-Project/TheBestBookOn.com#57]
There is currently no way to fetch a single user's observations.  Given a request with a username and OLID, our API should return a all observations submitted be a user for the given work (or a 404 error if none were found).  There should also be a way to fetch _all_ observations associated with a single user.

**Comment by mekarpeles** [comment]
This would be a good one for Shivam if they're up for it!

**Comment by jamesachamp** [comment]
Closing as observations will be stored in Open Library.
